6CS012 - Artificial Intelligence and Machine Learning


Task 1: Unit Converter

In [ ]:
def unit_converter():
    """
    Converts between different units of measurement (length, weight, volume).
    Prompts user for conversion type and value, then displays result.
    Handles invalid input with try-except.
    """
    print("Welcome to the Unit Converter!")
    print("Choose conversion type:")
    print("1. Length (meters - feet)")
    print("2. Weight (kilograms - pounds)")
    print("3. Volume (liters - gallons)")

    try:
        choice = int(input("Enter 1, 2, or 3: "))
        if choice not in [1, 2, 3]:
            print("Invalid choice. Please run again.")
            return

        value = float(input("Enter the value to convert: "))

        if choice == 1:  # Length
            print("Convert: 1. meters to feet, 2. feet to meters")
            sub = int(input("Enter 1 or 2: "))
            if sub == 1:
                result = value * 3.28084
                print(f"{value} m = {result:.2f} ft")
            elif sub == 2:
                result = value / 3.28084
                print(f"{value} ft = {result:.2f} m")
            else:
                print("Invalid sub-choice.")

        elif choice == 2:  # Weight
            print("Convert: 1. kg to lbs, 2. lbs to kg")
            sub = int(input("Enter 1 or 2: "))
            if sub == 1:
                result = value * 2.20462
                print(f"{value} kg = {result:.2f} lbs")
            elif sub == 2:
                result = value / 2.20462
                print(f"{value} lbs = {result:.2f} kg")
            else:
                print("Invalid sub-choice.")

        elif choice == 3:  # Volume
            print("Convert: 1. liters to gallons, 2. gallons to liters")
            sub = int(input("Enter 1 or 2: "))
            if sub == 1:
                result = value * 0.264172
                print(f"{value} L = {result:.2f} gal")
            elif sub == 2:
                result = value / 0.264172
                print(f"{value} gal = {result:.2f} L")
            else:
                print("Invalid sub-choice.")

    except ValueError:
        print("Error: Please enter numeric values only.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

# Run the converter
unit_converter()

Welcome to the Unit Converter!
Choose conversion type:
1. Length (meters - feet)
2. Weight (kilograms - pounds)
3. Volume (liters - gallons)


Enter 1, 2, or 3:  1
Enter the value to convert:  23


Convert: 1. meters to feet, 2. feet to meters


Enter 1 or 2:  2


23.0 ft = 7.01 m


This code cell defines a Python function `unit_converter` that allows users to convert between different units of measurement (length, weight, volume). It takes user input for the conversion type and value, performs the calculation, and prints the result, including error handling for invalid input.

Task 2: Mathematical Operations on a List


In [ ]:
def sum_numbers(numbers):
    """Return the sum of a list of numbers."""
    return sum(numbers)

def average(numbers):
    """Return the average of a list of numbers."""
    return sum(numbers) / len(numbers) if numbers else 0

def maximum(numbers):
    """Return the maximum of a list of numbers."""
    return max(numbers)

def minimum(numbers):
    """Return the minimum of a list of numbers."""
    return min(numbers)

def list_operations():
    """
    Prompts user for an operation and a list of numbers, then displays the result.
    Handles invalid input and empty lists.
    """
    print("Mathematical Operations on a List")
    print("Choose operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        op = int(input("Enter 1, 2, 3, or 4: "))
        if op not in [1, 2, 3, 4]:
            print("Invalid operation choice.")
            return

        numbers_input = input("Enter numbers separated by spaces: ")
        numbers = [float(x) for x in numbers_input.split()]

        if not numbers:
            print("The list is empty.")
            return

        if op == 1:
            result = sum_numbers(numbers)
            print(f"Sum = {result}")
        elif op == 2:
            result = average(numbers)
            print(f"Average = {result}")
        elif op == 3:
            result = maximum(numbers)
            print(f"Maximum = {result}")
        elif op == 4:
            result = minimum(numbers)
            print(f"Minimum = {result}")

    except ValueError:
        print("Error: Please enter numeric values only.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

# Run the operation
list_operations()

Mathematical Operations on a List
Choose operation:
1. Sum
2. Average
3. Maximum
4. Minimum


Enter 1, 2, 3, or 4:  3
Enter numbers separated by spaces:  3 4


Maximum = 4.0


This code cell defines several helper functions (`sum_numbers`, `average`, `maximum`, `minimum`) and a main function `list_operations`. The `list_operations` function prompts the user to select an operation (sum, average, max, min) to perform on a list of numbers provided by the user. It also includes error handling for invalid input and empty lists.

Exercise on List Manipulation

In [ ]:
# 1. Extract every other element
def extract_every_other(lst):
    """Return a new list containing every other element starting from first."""
    return lst[::2]

print(extract_every_other([1, 2, 3, 4, 5, 6]))  # [1, 3, 5]

# 2. Slice a sublist (start to end inclusive)
def get_sublist(lst, start, end):
    """Return sublist from start to end (inclusive)."""
    return lst[start:end+1]

print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))  # [3, 4, 5]

# 3. Reverse a list using slicing
def reverse_list(lst):
    """Return reversed list using slicing."""
    return lst[::-1]

print(reverse_list([1, 2, 3, 4, 5]))  # [5, 4, 3, 2, 1]

# 4. Remove first and last elements
def remove_first_last(lst):
    """Return sublist without first and last elements."""
    return lst[1:-1]

print(remove_first_last([1, 2, 3, 4, 5]))  # [2, 3, 4]

# 5. Get first n elements
def get_first_n(lst, n):
    """Return first n elements."""
    return lst[:n]

print(get_first_n([1, 2, 3, 4, 5], 3))  # [1, 2, 3]

# 6. Get last n elements
def get_last_n(lst, n):
    """Return last n elements."""
    return lst[-n:]

print(get_last_n([1, 2, 3, 4, 5], 2))  # [4, 5]

# 7. Reverse skip (every second element from second-to-last backward)
def reverse_skip(lst):
    """Return every second element starting from second-to-last, moving backward."""
    return lst[-2::-2]

print(reverse_skip([1, 2, 3, 4, 5, 6]))  # [5, 3, 1]

[1, 3, 5]
[3, 4, 5]
[5, 4, 3, 2, 1]
[2, 3, 4]
[1, 2, 3]
[4, 5]
[5, 3, 1]


Exercise on Nested List

In [ ]:
# 1. Flatten a nested list (one level)
def flatten(lst):
    """Flatten a list of lists into a single list."""
    result = []
    for sub in lst:
        result.extend(sub)
    return result

print(flatten([[1, 2], [3, 4], [5]]))  # [1, 2, 3, 4, 5]

# 2. Access nested list element using indices
def access_nested_element(lst, indices):
    """Return element at position given by indices list."""
    elem = lst
    for idx in indices:
        elem = elem[idx]
    return elem

print(access_nested_element([[1,2,3],[4,5,6],[7,8,9]], [1,2]))  # 6

# 3. Sum of all elements in a nested list (any depth)
def sum_nested(lst):
    """Return sum of all numbers in a nested list (recursive)."""
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

print(sum_nested([[1,2],[3,[4,5]],6]))  # 21

# 4. Remove specific element from nested list
def remove_element(lst, elem):
    """Remove all occurrences of elem from nested list (returns new list)."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result

print(remove_element([[1,2],[3,2],[4,5]], 2))  # [[1], [3], [4, 5]]

# 5. Find maximum element in nested list
def find_max(lst):
    """Return maximum element in nested list."""
    max_val = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_val = max(max_val, find_max(item))
        else:
            max_val = max(max_val, item)
    return max_val

print(find_max([[1,2],[3,[4,5]],6]))  # 6

# 6. Count occurrences of an element in nested list
def count_occurrences(lst, elem):
    """Count occurrences of elem in nested list."""
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

print(count_occurrences([[1,2],[2,3],[2,4]], 2))  # 3

# 7. Deep flatten (any depth)
def deep_flatten(lst):
    """Flatten a deeply nested list into a single list."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

print(deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]))  # [1,2,3,4,5,6,7,8]

# 8. Average of all elements in nested list
def average_nested(lst):
    """Return average of all numbers in nested list."""
    total = sum_nested(lst)
    count = count_elements(lst)  # need a helper to count elements
    return total / count if count else 0

def count_elements(lst):
    """Count total number of numeric elements in nested list."""
    cnt = 0
    for item in lst:
        if isinstance(item, list):
            cnt += count_elements(item)
        else:
            cnt += 1
    return cnt

print(average_nested([[1,2],[3,4],[5,6]]))  # 3.5

[1, 2, 3, 4, 5]
6
21
[[1], [3], [4, 5]]
6
3
[1, 2, 3, 4, 5, 6, 7, 8]
3.5


 NumPy Section

In [ ]:
import numpy as np

 Basic Vector and Matrix Operation with NumPy

Problem 1: Array Creation

In [ ]:
# 1. Empty array 2x2
empty_arr = np.empty((2, 2))
print("Empty 2x2:\n", empty_arr)

# 2. All ones 4x2
ones_arr = np.ones((4, 2))
print("Ones 4x2:\n", ones_arr)

# 3. Full array with fill value
full_arr = np.full((3, 3), 7)
print("Full 3x3 with 7:\n", full_arr)

# 4. Zeros like a given array
given = np.array([[1,2],[3,4]])
zeros_like_arr = np.zeros_like(given)
print("Zeros like given:\n", zeros_like_arr)

# 5. Ones like a given array
ones_like_arr = np.ones_like(given)
print("Ones like given:\n", ones_like_arr)

# 6. Convert list to numpy array
new_list = [1,2,3,4]
numpy_array = np.array(new_list)
print("Numpy array from list:", numpy_array)

Empty 2x2:
 [[2.12199579e-314 1.15224371e-311]
 [4.84184333e-321 1.15224371e-311]]
Ones 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Full 3x3 with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Zeros like given:
 [[0 0]
 [0 0]]
Ones like given:
 [[1 1]
 [1 1]]
Numpy array from list: [1 2 3 4]


Problem 2: Array Manipulation – Numerical Ranges and Indexing

In [ ]:
# 1. Values from 10 to 49
arr10_49 = np.arange(10, 50)
print("10 to 49:", arr10_49)

# 2. 3x3 matrix with values 0 to 8
arr0_8 = np.arange(9).reshape(3, 3)
print("3x3 0-8:\n", arr0_8)

# 3. 3x3 identity matrix
identity = np.eye(3)
print("Identity 3x3:\n", identity)

# 4. Random array of size 30 and mean
rand30 = np.random.random(30)
mean30 = rand30.mean()
print("Mean of random 30:", mean30)

# 5. 10x10 random array min and max
rand10x10 = np.random.random((10, 10))
print("Min:", rand10x10.min(), "Max:", rand10x10.max())

# 6. Zero array size 10, replace 5th element with 1
zero10 = np.zeros(10)
zero10[4] = 1  # 5th element (index 4)
print("Zero10 with 5th=1:", zero10)

# 7. Reverse array arr = [1,2,0,0,4,0]
arr = np.array([1,2,0,0,4,0])
reversed_arr = arr[::-1]
print("Reversed:", reversed_arr)

# 8. 2d array with 1 on border and 0 inside (e.g., 5x5)
border = np.ones((5,5))
border[1:-1, 1:-1] = 0
print("Border 1 inside 0:\n", border)

# 9. 8x8 checkerboard pattern
checkerboard = np.zeros((8,8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("Checkerboard 8x8:\n", checkerboard)

10 to 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
3x3 0-8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Identity 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Mean of random 30: 0.48640145472660967
Min: 0.016166248666378502 Max: 0.9988014095716649
Zero10 with 5th=1: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Reversed: [0 4 0 0 2 1]
Border 1 inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
Checkerboard 8x8:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem 3: Array Operations

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 1. Add x and y
print("x + y =\n", x + y)

# 2. Subtract x and y
print("x - y =\n", x - y)

# 3. Multiply array by integer (e.g., x * 3)
print("x * 3 =\n", x * 3)

# 4. Square of each element
print("x squared =\n", x ** 2)

# 5. Dot products
print("v · w =", np.dot(v, w))
print("x · v =", np.dot(x, v))
print("x · y =\n", np.dot(x, y))

# 6. Concatenate x and y along rows (axis=0) and v and w along columns (axis=0 for 1D? v and w are 1D, so stacking as rows)
concat_xy_row = np.concatenate((x, y), axis=0)
print("x and y concatenated along rows:\n", concat_xy_row)

# For v and w, to concatenate along columns we need to make them column vectors or use column_stack
vw_col = np.column_stack((v, w))
print("v and w as columns:\n", vw_col)

# 7. Concatenate x and v
try:
    np.concatenate((x, v), axis=0)
except ValueError as e:
    print("Error when concatenating x and v:", e)
    print("Explanation: x is 2D (2,2) and v is 1D (2,). NumPy cannot concatenate arrays of different dimensions along axis 0 unless we reshape v to match.")

x + y =
 [[ 6  8]
 [10 13]]
x - y =
 [[-4 -4]
 [-4 -3]]
x * 3 =
 [[ 3  6]
 [ 9 15]]
x squared =
 [[ 1  4]
 [ 9 25]]
v · w = 219
x · v = [29 77]
x · y =
 [[19 22]
 [50 58]]
x and y concatenated along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
v and w as columns:
 [[ 9 11]
 [10 12]]
Error when concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x is 2D (2,2) and v is 1D (2,). NumPy cannot concatenate arrays of different dimensions along axis 0 unless we reshape v to match.


Problem 4: Matrix Operations

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("A * A_inv =\n", I)
print("Is identity? (close to due to floating point):\n", np.allclose(I, np.eye(2)))

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB =\n", AB)
print("BA =\n", BA)
print("AB == BA?", np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T A^T
AB_T = AB.T
B_T_A_T = np.dot(B.T, A.T)
print("(AB)^T =\n", AB_T)
print("B^T A^T =\n", B_T_A_T)
print("Equal?", np.array_equal(AB_T, B_T_A_T))

# Solve linear system using inverse method
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9
A_sys = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3, 1, -1]])
B_sys = np.array([-1, -3, 9])

# Using inverse
A_inv_sys = np.linalg.inv(A_sys)
X = np.dot(A_inv_sys, B_sys)
print("Solution using inverse:", X)

# Using np.linalg.solve (more efficient)
X_solve = np.linalg.solve(A_sys, B_sys)
print("Solution using solve:", X_solve)

A * A_inv =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is identity? (close to due to floating point):
 True
AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
AB == BA? False
(AB)^T =
 [[23 51]
 [13 29]]
B^T A^T =
 [[23 51]
 [13 29]]
Equal? True
Solution using inverse: [ 2.  1. -2.]
Solution using solve: [ 2.  1. -2.]


This code cell contains several Python functions demonstrating list manipulation techniques using slicing. These include extracting every other element, slicing a sublist, reversing a list, removing first/last elements, getting first/last `n` elements, and a function for reverse skipping elements.

This code cell illustrates key matrix operations and properties using NumPy. It includes proving `A * A^-1 = I` (identity matrix), demonstrating that matrix multiplication is not commutative (`AB != BA`), proving the transpose property `(AB)^T = B^T A^T`, and solving a system of linear equations using both matrix inversion and `np.linalg.solve`.

 Experiment: How Fast is NumPy?

This cell imports the NumPy library, which is a fundamental package for numerical computing in Python. It assigns the alias `np` to NumPy for easier use in the code.

This code cell contains multiple Python functions designed to perform operations on nested lists. These include flattening a nested list (one level or deep), accessing elements by indices, summing all elements (any depth), removing specific elements, finding the maximum element, counting occurrences, and calculating the average of all elements.

This code cell demonstrates various ways to create NumPy arrays, including initializing empty arrays, arrays filled with ones, arrays filled with a specified value, arrays of zeros/ones with the same shape as an existing array, and converting a standard Python list into a NumPy array.

This code cell showcases different NumPy array manipulation techniques. It includes creating arrays with numerical ranges, reshaping arrays, creating identity matrices, generating random arrays and calculating their statistics (mean, min, max), modifying specific elements, reversing arrays, creating arrays with borders, and generating a checkerboard pattern using slicing.

This code cell demonstrates fundamental arithmetic operations and linear algebra operations using NumPy arrays. It covers element-wise addition, subtraction, scalar multiplication, squaring, dot products between vectors and matrices, and concatenation of arrays, also illustrating a common error when concatenating arrays of different dimensions.

In [ ]:
import time

size = 1_000_000
a_list = list(range(size))
b_list = list(range(size))

a_np = np.arange(size)
b_np = np.arange(size)

# 1. Element-wise addition
start = time.time()
c_list = [a_list[i] + b_list[i] for i in range(size)]
end = time.time()
print(f"List addition took: {end - start:.5f} seconds")

start = time.time()
c_np = a_np + b_np
end = time.time()
print(f"NumPy addition took: {end - start:.5f} seconds")

# 2. Element-wise multiplication
start = time.time()
c_list = [a_list[i] * b_list[i] for i in range(size)]
end = time.time()
print(f"List multiplication took: {end - start:.5f} seconds")

start = time.time()
c_np = a_np * b_np
end = time.time()
print(f"NumPy multiplication took: {end - start:.5f} seconds")

# 3. Dot product
start = time.time()
dot_list = sum(a_list[i] * b_list[i] for i in range(size))
end = time.time()
print(f"List dot product took: {end - start:.5f} seconds")

start = time.time()
dot_np = np.dot(a_np, b_np)
end = time.time()
print(f"NumPy dot product took: {end - start:.5f} seconds")

# 4. Matrix multiplication (1000x1000)
size_mat = 1000
A_list = [[i*j for j in range(size_mat)] for i in range(size_mat)]
B_list = [[i+j for j in range(size_mat)] for i in range(size_mat)]

A_np = np.array(A_list)
B_np = np.array(B_list)

# Matrix multiplication using list comprehension (triple loop)
def mat_mult_list(A, B):
    n = len(A)
    C = [[0]*n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            s = 0
            for k in range(n):
                s += A[i][k] * B[k][j]
            C[i][j] = s
    return C

start = time.time()
C_list = mat_mult_list(A_list, B_list)
end = time.time()
print(f"List matrix multiplication (1000x1000) took: {end - start:.5f} seconds")

start = time.time()
C_np = np.dot(A_np, B_np)
end = time.time()
print(f"NumPy matrix multiplication (1000x1000) took: {end - start:.5f} seconds")

List addition took: 0.05543 seconds
NumPy addition took: 0.00139 seconds
List multiplication took: 0.06137 seconds
NumPy multiplication took: 0.00157 seconds
List dot product took: 0.05642 seconds
NumPy dot product took: 0.00098 seconds


This code cell conducts a performance comparison between standard Python lists and NumPy arrays for common numerical operations like element-wise addition, multiplication, dot product, and matrix multiplication. The goal is to demonstrate NumPy's significant speed advantage for large datasets by measuring execution time for each operation.

Expected Observations: NumPy operations will be orders of magnitude faster than pure Python loops, especially for large arrays/matrices. The list-based matrix multiplication will be extremely slow (possibly minutes), while NumPy will finish in seconds or less.